### ISSUE TITLE
How do you include Openssl?

### ISSUE THREAD

**Issue by fooloomanzoo** [R00T88/CSMTP#1]
Hi,

I am asking because I have problems to compile [SMTP Client with SSL/TLS](https://www.codeproject.com/Articles/98355/SMTP-Client-with-SSL-TLS?msg=5365552#xx5365552xx) where you modified the CSmtp-Class. That's why I found your solution, but still have problems to include openssl. How do you do it in your project?

Regards

**Comment by R00T88** [comment]
Hello,
i download OpenSSL for windows https://slproweb.com/products/Win32OpenSSL.html and the add headers and libs to project.

Regards

**Comment by fooloomanzoo** [comment]
I installed openssl from that website, but I also tried a self-compiled version using this [site](http://p-nand-q.com/programming/windows/building_openssl_with_visual_studio_2013.html).

Which directories would you then include in your dependencies and how are you doing it in Visual Studio?

I tried:
- _C:\OpenSSL-Win32\include_   **into**   _Properties --> C/C++ --> General --> Additional Include Dependencies_
- _C:\OpenSSL-Win32\lib_   **into**   _Properties --> Linker --> General --> Additional Library Directories_

And the output is still:
`fatal error C1083: File (Include) can not be opened: "openssl\ssl.h": No such file or directory`

Sorry, the problem might be very ordinary and is more related to the project in Visual Studio, but I can't make it to work. 

Regards

**Comment by fooloomanzoo** [comment]
It is not clear to me how you did include the dependencies to your project
